export const municipios = [
    { nome: 'Abaiara', link: 'http://tributario.aspec.com.br/portal.ce.abaiara/UC0084EmitirCertidao/T0084L-emitir-certidao-tributos-municipais.xhtml'},
    // { nome: 'Acarape', link: ''},
    { nome: 'Acaraú', link: 'https://servicos2.speedgov.com.br/acarau/pages/certidao_contribuinte'},
    // { nome: 'Acopiara', link: ''},
    // { nome: 'Aiuaba', link: ''},
    // { nome: 'Alcântaras', link: ''},
    // { nome: 'Altaneira', link: ''},
    // { nome: 'Alto Santo', link: ''},
    { nome: 'Amontada', link: 'https://servicos2.speedgov.com.br/amontada/pages/certidao_contribuinte'},
    // { nome: 'Antonina do Norte', link: ''},
    // { nome: 'Apuiarés', link: ''},
    { nome: 'Aquiraz', link: 'https://servicos2.speedgov.com.br/aquiraz/pages/certidao_contribuinte'},
    { nome: 'Aracati', link: 'https://servicos2.speedgov.com.br/aracati/pages/certidao_contribuinte'},
    // { nome: 'Aracoiaba', link: ''},
    // { nome: 'Ararendá', link: ''},
    { nome: 'Araripe', link: 'https://servicos2.speedgov.com.br/araripe/pages/certidao_contribuinte'},
    // { nome: 'Aratuba', link: ''},
    // { nome: 'Arneiroz', link: ''},
    // { nome: 'Assaré', link: ''},
    // { nome: 'Aurora', link: ''},
    // { nome: 'Baixio', link: ''},
    // { nome: 'Banabuiú', link: ''},
    // { nome: 'Barbalha', link: ''},
    // { nome: 'Barreira', link: ''},
    // { nome: 'Barro', link: ''},
    // { nome: 'Barroquinha', link: ''},
    // { nome: 'Baturité', link: ''},
    { nome: 'Beberibe', link: 'https://servicos2.speedgov.com.br/beberibe/pages/certidao_contribuinte'},
    // { nome: 'Bela Cruz', link: ''},
    // { nome: 'Boa Viagem', link: ''},
    // { nome: 'Brejo Santo', link: ''},
    { nome: 'Camocim', link: 'https://servicos2.speedgov.com.br/camocim/pages/certidao_contribuinte'},
    // { nome: 'Campos Sales', link: ''},
    { nome: 'Canindé', link: 'https://servicos2.speedgov.com.br/caninde/pages/certidao_contribuinte'},
    // { nome: 'Capistrano', link: ''},
    // { nome: 'Caridade', link: ''},
    // { nome: 'Cariré', link: ''},
    // { nome: 'Caririaçu', link: ''},
    // { nome: 'Cariús', link: ''},
    { nome: 'Carnaubal', link: 'https://servicos2.speedgov.com.br/carnaubal/pages/certidao_contribuinte'},
    { nome: 'Cascavel', link: 'https://servicos2.speedgov.com.br/cascavel/pages/certidao_contribuinte'},
    // { nome: 'Catarina', link: ''},
    // { nome: 'Catunda', link: ''},
    { nome: 'Caucaia', link: 'http://sefin.caucaia.ce.gov.br/emissao-cert-negativa-trib-municipais/'},
    // { nome: 'Cedro', link: ''},
    // { nome: 'Chaval', link: ''},
    // { nome: 'Choró', link: ''},
    // { nome: 'Chorozinho', link: ''},
    // { nome: 'Coreaú', link: ''},
    // { nome: 'Crateús', link: ''},
    { nome: 'Crato', link: 'https://servicos2.speedgov.com.br/crato/pages/certidao_contribuinte'},
    // { nome: 'Croatá', link: ''},
    { nome: 'Cruz', link: 'https://servicos2.speedgov.com.br/cruz/pages/certidao_contribuinte'},
    // { nome: 'Deputado Irapuan Pinheiro', link: ''},
    // { nome: 'Ereré', link: ''},
    { nome: 'Eusébio', link: 'https://servicos2.speedgov.com.br/eusebio/pages/certidao_contribuinte'},
    // { nome: 'Farias Brito', link: ''},
    // { nome: 'Forquilha', link: ''},
    { nome: 'Fortaleza', link: 'https://grpfor.sefin.fortaleza.ce.gov.br/grpfor/pagesPublic/certidoes/emitirCertidao.seam'},
    { nome: 'Fortim', link: 'https://servicos2.speedgov.com.br/fortim/pages/certidao_contribuinte'},
    // { nome: 'Frecheirinha', link: ''},
    // { nome: 'General Sampaio', link: ''},
    // { nome: 'Graça', link: ''},
    // { nome: 'Granja', link: ''},
    // { nome: 'Granjeiro', link: ''},
    // { nome: 'Groaíras', link: ''},
    { nome: 'Guaiúba', link: 'https://servicos2.speedgov.com.br/guaiuba/pages/certidao_contribuinte'},
    // { nome: 'Guaraciaba do Norte', link: ''},
    { nome: 'Guaramiranga', link: 'https://servicos2.speedgov.com.br/guaramiranga/pages/certidao_contribuinte'},
    // { nome: 'Hidrolândia', link: ''},
    { nome: 'Horizonte', link: 'https://servicos2.speedgov.com.br/horizonte/pages/certidao_contribuinte'},
    // { nome: 'Ibaretama', link: ''},
    // { nome: 'Ibiapina', link: ''},
    // { nome: 'Ibicuitinga', link: ''},
    { nome: 'Icapuí', link: 'https://servicos2.speedgov.com.br/icapui/pages/certidao_contribuinte'},
    // { nome: 'Icó', link: ''},
    { nome: 'Iguatu', link: 'https://servicos2.speedgov.com.br/iguatu/pages/certidao_contribuinte'},
    // { nome: 'Independência', link: ''},
    // { nome: 'Ipaporanga', link: ''},
    // { nome: 'Ipaumirim', link: ''},
    { nome: 'Ipu', link: 'https://servicos2.speedgov.com.br/ipu/pages/certidao_contribuinte'},
    // { nome: 'Ipueiras', link: ''},
    // { nome: 'Iracema', link: ''},
    // { nome: 'Irauçuba', link: ''},
    // { nome: 'Itaiçaba', link: ''},
    // { nome: 'Itaitinga', link: ''},
    // { nome: 'Itapajé', link: ''},
    { nome: 'Itapipoca', link: 'https://servicos2.speedgov.com.br/itapipoca/pages/certidao_contribuinte'},
    // { nome: 'Itapiúna', link: ''},
    // { nome: 'Itarema', link: ''},
    // { nome: 'Itatira', link: ''},
    // { nome: 'Jaguaretama', link: ''},
    // { nome: 'Jaguaribara', link: ''},
    { nome: 'Jaguaribe', link: 'https://servicos2.speedgov.com.br/jaguaribe/pages/certidao_contribuinte'},
    // { nome: 'Jaguaruana', link: ''},
    // { nome: 'Jardim', link: ''},
    // { nome: 'Jati', link: ''},
    // { nome: 'Jijoca de Jericoacoara', link: ''},
    { nome: 'Juazeiro do Norte', link: 'https://servicos2.speedgov.com.br/juazeirodonorte/pages/certidao_contribuinte'},
    { nome: 'Jucás', link: 'https://servicos2.speedgov.com.br/jucas/pages/certidao_contribuinte'},
    // { nome: 'Lavras da Mangabeira', link: ''},
    { nome: 'Limoeiro do Norte', link: 'https://servicos2.speedgov.com.br/limoeirodonorte/pages/certidao_contribuinte'},
    // { nome: 'Madalena', link: ''},
    { nome: 'Maracanaú', link: 'https://servicos2.speedgov.com.br/maracanau/pages/certidao_contribuinte'},
    { nome: 'Maranguape', link: 'https://servicos2.speedgov.com.br/maranguape/pages/certidao_contribuinte'},
    // { nome: 'Marco', link: ''},
    // { nome: 'Martinópole', link: ''},
    // { nome: 'Massapê', link: ''},
    // { nome: 'Mauriti', link: ''},
    // { nome: 'Meruoca', link: ''},
    // { nome: 'Milagres', link: ''},
    // { nome: 'Milhã', link: ''},
    // { nome: 'Miraíma', link: ''},
    // { nome: 'Missão Velha', link: ''},
    { nome: 'Mombaça', link: 'https://servicos2.speedgov.com.br/monbaca/pages/certidao_contribuinte'},
    // { nome: 'Monsenhor Tabosa', link: ''},
    { nome: 'Morada Nova', link: 'https://servicos2.speedgov.com.br/moradanova/pages/certidao_contribuinte'},
    // { nome: 'Moraújo', link: ''},
    // { nome: 'Morrinhos', link: ''},
    // { nome: 'Mucambo', link: ''},
    // { nome: 'Mulungu', link: ''},
    // { nome: 'Nova Olinda', link: ''},
    { nome: 'Nova Russas', link: 'https://servicos2.speedgov.com.br/novarussas/pages/certidao_contribuinte'},
    // { nome: 'Novo Oriente', link: ''},
    // { nome: 'Ocara', link: ''},
    // { nome: 'Orós', link: ''},
    { nome: 'Pacajus', link: 'https://servicos2.speedgov.com.br/pacajus/pages/certidao_contribuinte'},
    { nome: 'Pacatuba', link: 'https://sam.pacatuba.gerentemunicipal.com.br/contribuinte/cnd'},
    // { nome: 'Pacoti', link: ''},
    // { nome: 'Pacujá', link: ''},
    // { nome: 'Palhano', link: ''},
    // { nome: 'Palmácia', link: ''},
    { nome: 'Paracuru', link: 'https://servicos2.speedgov.com.br/paracuru/pages/certidao_contribuinte'},
    // { nome: 'Paraipaba', link: ''},
    // { nome: 'Parambu', link: ''},
    // { nome: 'Paramoti', link: ''},
    // { nome: 'Pedra Branca', link: ''},
    // { nome: 'Penaforte', link: ''},
    // { nome: 'Pentecoste', link: ''},
    // { nome: 'Pereiro', link: ''},
    // { nome: 'Pindoretama', link: ''},
    // { nome: 'Piquet Carneiro', link: ''},
    // { nome: 'Pires Ferreira', link: ''},
    // { nome: 'Poranga', link: ''},
    // { nome: 'Porteiras', link: ''},
    // { nome: 'Potengi', link: ''},
    // { nome: 'Potiretama', link: ''},
    // { nome: 'Quiterianópolis', link: ''},
    // { nome: 'Quixadá', link: ''},
    // { nome: 'Quixelô', link: ''},
    { nome: 'Quixeramobim', link: 'https://servicos2.speedgov.com.br/quixeramobim/pages/certidao_contribuinte'},
    // { nome: 'Quixeré', link: ''},
    { nome: 'Redenção', link: 'https://redencao.ssinformatica.net/portal/web/certidao/contribuinte/documento;jsessionid=e3E6nW06cZJ2ofO7jWRLwKMXYouZDmgwNf-9uM1M.redencao-portal-5575cdf9b9-8qgpr'},
    // { nome: 'Reriutaba', link: ''},
    { nome: 'Russas', link: 'https://russas.ssinformatica.net/portal/web/certidao/contribuinte/documento;jsessionid=BvEctMRGAXRCjB6AAIJhEkn6MqfaAESSQKDIPojy.russas-portal-7864f65d96-qq22q'},
    // { nome: 'Saboeiro', link: ''},
    // { nome: 'Salitre', link: ''},
    // { nome: 'Santa Quitéria', link: ''},
    // { nome: 'Santana do Acaraú', link: ''},
    // { nome: 'Santana do Cariri', link: ''},
    // { nome: 'São Benedito', link: ''},
    { nome: 'São Gonçalo do Amarante', link: 'https://fisco.pmsga.ce.gov.br/divida-ativa/certidao-negativa/emissor-publico-certidao-negativa'},
    // { nome: 'São João do Jaguaribe', link: ''},
    // { nome: 'São Luís do Curu', link: ''},
    // { nome: 'Senador Pompeu', link: ''},
    // { nome: 'Senador Sá', link: ''},
    { nome: 'Sobral', link: 'https://servicos2.speedgov.com.br/sobral/pages/certidao_contribuinte'},
    // { nome: 'Solonópole', link: ''},
    // { nome: 'Tabuleiro do Norte', link: ''},
    // { nome: 'Tamboril', link: ''},
    // { nome: 'Tarrafas', link: ''},
    { nome: 'Tauá', link: 'https://servicos2.speedgov.com.br/taua/pages/certidao_contribuinte'},
    // { nome: 'Tejuçuoca', link: ''},
    { nome: 'Tianguá', link: 'http://servicos2.speedgov.com.br/tiangua/pages/certidao_contribuinte'},
    { nome: 'Trairi', link: 'http://servicos2.speedgov.com.br/trairi/pages/certidao_contribuinte'},
    // { nome: 'Tururu', link: ''},
    // { nome: 'Ubajara', link: ''},
    // { nome: 'Umari', link: ''},
    // { nome: 'Umirim', link: ''},
    // { nome: 'Uruburetama', link: ''},
    { nome: 'Uruoca', link: 'https://uruoca.ssinformatica.net/portal/web/certidao/contribuinte/documento;jsessionid=THlt7bct1seOcIR8chimwiE_xC7NVnpM6O3T0_2C.varzeaalegre-portal-6b887d7b87-nkb72'},
    // { nome: 'Varjota', link: ''},
    { nome: 'Várzea Alegre', link: 'https://varzeaalegre.ssinformatica.net/portal/web/certidao/contribuinte/documento;jsessionid=THlt7bct1seOcIR8chimwiE_xC7NVnpM6O3T0_2C.varzeaalegre-portal-6b887d7b87-nkb72'},
    { nome: 'Viçosa do Ceará', link: 'https://servicos2.speedgov.com.br/vicosadoceara/pages/certidao_contribuinte'},
]